apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    app: core-project-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: core-project-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
