{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core-project-service.fullname" . }}-secret
  labels:
    {{- include "core-project-service.labels" . | nindent 4 }}
type: Opaque
data: {}
{{- end }}
